_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": global_step
              "6":
                - 3
              "7": []
            - "1": peak_memory_reserved
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": peak_memory_alloc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": lr
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": tokens_per_second_per_gpu
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": peak_memory_active
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 49
                - 51
                - 55
                - 105
            "2":
                - 1
                - 49
                - 51
                - 55
                - 105
            "3":
                - 3
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 5
            "9":
                "2": torchtune
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 4
checkpointer:
    value:
        _component_: torchtune.training.FullModelHFCheckpointer
        checkpoint_dir: /tmp/Llama-3.2-3B/
        checkpoint_files:
            - model-00001-of-00002.safetensors
            - model-00002-of-00002.safetensors
        model_type: LLAMA3_2
        output_dir: /tmp/Llama-3.2-3B/
        recipe_checkpoint: null
compile:
    value: false
dataset:
    value:
        _component_: torchtune.datasets.text_completion_dataset
        column: input
        data_files: datasets/triton_functions.json
        source: json
        split: train
device:
    value: cuda
dtype:
    value: bf16
enable_activation_checkpointing:
    value: true
epochs:
    value: 1
gradient_accumulation_steps:
    value: 1
log_every_n_steps:
    value: 1
log_peak_memory_stats:
    value: true
loss:
    value:
        _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch:
    value: null
metric_logger:
    value:
        _component_: torchtune.training.metric_logging.WandBLogger
        project: torchtune
model:
    value:
        _component_: torchtune.models.llama3_2.llama3_2_3b
optimizer:
    value:
        _component_: bitsandbytes.optim.PagedAdamW8bit
        lr: 2e-05
optimizer_in_bwd:
    value: true
output_dir:
    value: /tmp/full-llama3.2-finetune
profiler:
    value:
        _component_: torchtune.training.setup_torch_profiler
        active_steps: 1
        cpu: true
        cuda: true
        enabled: false
        num_cycles: 1
        output_dir: /tmp/full-llama3.2-finetune/profiling_outputs
        profile_memory: true
        record_shapes: true
        wait_steps: 1
        warmup_steps: 2
        with_flops: false
        with_stack: false
resume_from_checkpoint:
    value: false
seed:
    value: null
shuffle:
    value: true
tokenizer:
    value:
        _component_: torchtune.models.llama3.llama3_tokenizer
        max_seq_len: null
        path: /tmp/Llama-3.2-3B/original/tokenizer.model
