_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": global_step
              "6":
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 49
                - 51
                - 55
                - 105
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 105
            "3":
                - 3
                - 7
                - 23
                - 55
                - 66
            "4": 3.11.10
            "5": 0.18.7
            "8":
                - 5
            "9":
                "2": torchtune
            "12": 0.18.7
            "13": linux-x86_64
batch_size:
    value: 2
checkpointer:
    value:
        _component_: torchtune.training.FullModelHFCheckpointer
        checkpoint_dir: /tmp/Llama-3.2-11B-Vision-Instruct/
        checkpoint_files:
            - model-00001-of-00005.safetensors
            - model-00002-of-00005.safetensors
            - model-00003-of-00005.safetensors
            - model-00004-of-00005.safetensors
            - model-00005-of-00005.safetensors
        model_type: LLAMA3_VISION
        output_dir: /tmp/Llama-3.2-11B-Vision-Instruct/
        recipe_checkpoint: null
clip_grad_norm:
    value: 1
collate_fn:
    value: torchtune.data.padded_collate_tiled_images_and_mask
compile:
    value: false
custom_sharded_layers:
    value:
        - decoder.tok_embeddings
dataset:
    value:
        _component_: torchtune.datasets.text_completion_dataset
        column: input
        data_files: datasets/triton_functions.json
        source: json
        split: train
device:
    value: cuda
dtype:
    value: bf16
enable_activation_checkpointing:
    value: true
epochs:
    value: 1
gradient_accumulation_steps:
    value: 8
log_every_n_steps:
    value: 1
log_peak_memory_stats:
    value: true
loss:
    value:
        _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch:
    value: null
metric_logger:
    value:
        _component_: torchtune.training.metric_logging.WandBLogger
        project: torchtune
model:
    value:
        _component_: torchtune.models.llama3_2_vision.llama3_2_vision_11b
        decoder_trainable: false
        encoder_trainable: true
        fusion_trainable: true
        image_size: 560
optimizer:
    value:
        _component_: torch.optim.AdamW
        fused: true
        lr: 2e-05
optimizer_in_bwd:
    value: false
output_dir:
    value: /tmp/full-llama3.2-finetune-11b
profiler:
    value:
        _component_: torchtune.training.setup_torch_profiler
        active_steps: 2
        cpu: true
        cuda: true
        enabled: false
        num_cycles: 1
        output_dir: /tmp/full-llama3.2-finetune-11b/profiling_outputs
        profile_memory: false
        record_shapes: true
        wait_steps: 5
        warmup_steps: 3
        with_flops: false
        with_stack: false
resume_from_checkpoint:
    value: false
seed:
    value: null
shuffle:
    value: true
tokenizer:
    value:
        _component_: torchtune.models.llama3_2_vision.llama3_2_vision_transform
        image_size: 560
        max_seq_len: 8192
        path: /tmp/Llama-3.2-11B-Vision-Instruct/original/tokenizer.model
